[package]
name = "pdcp-sim"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true

[build-dependencies]
rasn-compiler = { path = "../rasn-compiler" }

[dependencies]
rasn = "0.27.2"
