[package]
name = "internal_macros"
publish = false
description = "Internal derive macros for rasn."
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
quote = "1.0.7"
proc-macro2 = "1.0.19"
